/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
//    id ("com.github.ryuzu.java-conventions")
    id("java-library")
    id("maven-publish")
    id("com.gradleup.shadow") version "9.4.1"
}

allprojects {
    group = "com.github.ryuzu"
    version = "1.0.7+1.21.11"

    repositories {
        mavenLocal()
        maven("https://repo.papermc.io/repository/maven-public/")
        mavenCentral()
        maven("https://jitpack.io")
        maven("https://repo.codemc.io/repository/maven-public/")
        maven("https://maven.citizensnpcs.co/repo")
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

subprojects {
    plugins.withType<JavaPlugin> {
        extensions.configure<JavaPluginExtension> {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }
}

dependencies {
    api(project(":searchableinfiniteshop-plugin"))
    api(project(":searchableinfiniteshop-v21newer"))
    api(project(":searchableinfiniteshop-commandlib"))
    api(project(":searchableinfiniteshop-api"))
}

java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21
description = "Searchable Infinite Shop Plugin"

publishing {
    repositories {
        maven {
            name = "repo"
            credentials(PasswordCredentials::class)
            url = uri(
                if (project.version.toString().endsWith("-SNAPSHOT"))
                    "https://maven.azisaba.net/snapshots"
                else
                    "https://maven.azisaba.net/releases"
            )
        }
    }

    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
}
