/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
//    id ("com.github.ryuzu.java-conventions")
    id("java-library")
    id("maven-publish")
    id("com.gradleup.shadow") version "9.4.1"
}

allprojects {
    repositories {
        mavenLocal()
        maven("https://repo.papermc.io/repository/maven-public/")
        mavenCentral()
        maven("https://jitpack.io")
        maven("https://repo.codemc.io/repository/maven-public/")
        maven("https://maven.citizensnpcs.co/repo")
    }
}

group = "com.github.ryuzu"
version = "1.0.0"

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

dependencies {
    api(project(":searchableinfiniteshop-plugin"))
    api(project(":searchableinfiniteshop-v16newer"))
    api(project(":searchableinfiniteshop-v16older"))
    api(project(":searchableinfiniteshop-api"))
}

java.sourceCompatibility = JavaVersion.VERSION_21
description = "Searchable Infinite Shop Plugin"

publishing {
    repositories {
        maven {
            name = "repo"
            credentials(PasswordCredentials::class)
            url =
                uri(
                    if (project.version.toString().endsWith("SNAPSHOT")) {
                        project.findProperty("deploySnapshotURL")
                            ?: System.getProperty("deploySnapshotURL", "https://repo.azisaba.net/repository/maven-snapshots/")
                    } else {
                        project.findProperty("deployReleasesURL")
                            ?: System.getProperty("deployReleasesURL", "https://repo.azisaba.net/repository/maven-releases/")
                    },
                )
        }
    }

    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
}
