/*
 * This file was generated by the Gradle "init" task.
 */

rootProject.name = "SearchableInfiniteShop"
include(":searchableinfiniteshop-api")
include(":searchableinfiniteshop-commandlib")
include(":searchableinfiniteshop-v21newer")
include(":searchableinfiniteshop-plugin")
project(":searchableinfiniteshop-plugin").projectDir = file("plugin")
project(":searchableinfiniteshop-api").projectDir = file("api")
project(":searchableinfiniteshop-commandlib").projectDir = file("commandlib")
project(":searchableinfiniteshop-v21newer").projectDir = file("v21newer")
