/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    id("java")
    id("java-library")
    id("maven-publish")
    id("com.gradleup.shadow") version "9.4.1"
}

repositories {
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }
    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://mvn.lumine.io/repository/maven-public/")
    }
    maven {
        url = uri("https://nexus.lichtspiele.org/repository/releases/")
    }
    maven {
        url = uri("https://libraries.minecraft.net/")
    }
    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }
}

dependencies {
    implementation("com.saicone.rtag:rtag:1.4.2")
    implementation("com.saicone.rtag:rtag-entity:1.4.2")
    implementation("com.saicone.rtag:rtag-item:1.4.2")
//    implementation("de.tr7zw:item-nbt-api:2.12.0")
    api("com.google.guava:guava:31.1-jre")
    api(project(":searchableinfiniteshop-v21newer"))
    api(project(":searchableinfiniteshop-v16newer"))
    api(project(":searchableinfiniteshop-v16older"))
    api(project(":searchableinfiniteshop-commandlib"))
    api(project(":searchableinfiniteshop-api"))
    compileOnly("org.spigotmc:spigot-api:1.21.11-R0.1-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")
    compileOnly("com.mojang:authlib:1.5.21")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("net.citizensnpcs:citizens-main:2.0.30-SNAPSHOT") {
        exclude("*", "*")
    }

    testImplementation("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    testImplementation("org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.110.0") {
        exclude(group = "org.junit.jupiter")
        exclude(group = "org.junit.platform")
        exclude(group = "org.opentest4j")
    }
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")
    testImplementation("org.mockito:mockito-core:5.14.2")
    testImplementation("org.mockito:mockito-junit-jupiter:5.14.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.12.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.12.1")
}

tasks {
    shadowJar {
        // Relocate rtag (DO NOT IGNORE THIS)
        relocate("com.saicone.rtag", "${project.group}.libs.rtag")
        // Exclude unused classes (optional)
        minimize()
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
